@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyModuleBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class ModuleBook
Class ReadOnlyModuleBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Module {
Class ArchivedModule
Class ArchivedModuleList
Class Module
Class UniqueModuleList
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModuleBook .up.|> ReadOnlyModuleBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" ModuleBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ModuleBook *--> "1" UniqueModuleList
UniqueModuleList o--> "*" Module
ModuleBook *--> "1" ArchivedModuleList
ArchivedModuleList o--> "*" ArchivedModule
Module *-right-> "1" ArchivedModule

ModelManager -->"*" Module : filtered list
@enduml
